### ISSUE TITLE
Course info screen is not scrollable

### ISSUE THREAD

**Issue by nick-hoang** [mitesh77/Best-Flutter-UI-Templates#64]
**To Reproduce**
1. Go to Home screen
2. Click on Design course (the last item)
3. Click to any item
4. See issue

**Expected behavior**
The course info screen is scrollable when the description text is long

**Screenshots**
![Screenshot_1610078907](https://user-images.githubusercontent.com/4602123/103973390-ea743180-51a1-11eb-8d2c-685a09b76fdc.png)

**Smartphone (please complete the following information):**
 - Device: Nexus 5X emulator
 - OS: android 9

**Comment by aniketambore** [comment]
This issue is not related to the current code base, check 

```
📁Best-Flutter-UI-Templates
    📁best_flutter_ui_templates
        📁lib
           📁design_course
               🎯course_info_screen.dart - line 179
```
As stated in **🎯course_info_screen.dart - line 179** the **Text** widget is using **maxLines: 3** property, which indicated that If the text exceeds the given number of lines, it will be truncated.

The exact behavior as per the code-base looks something like this
![Screenshot_1612529173](https://user-images.githubusercontent.com/52826253/107036608-ea3a7680-67df-11eb-8fbc-4fa8a66bcf93.png)

**Comment by aniketambore** [comment]
> 
> 
> **To Reproduce**
> Steps to reproduce the behavior:
> 
>     1. Go to Home screen
> 
>     2. Click on Design course (the last item)
> 
>     3. Click to any item
> 
>     4. See issue
> 
> 
> **Expected behavior**
> The course info screen is scrollable when the description text is long
> 
> **Screenshots**
> ![Screenshot_1610078907](https://user-images.githubusercontent.com/4602123/103973390-ea743180-51a1-11eb-8d2c-685a09b76fdc.png)
> 
> **Smartphone (please complete the following information):**
> 
>     * Device: Nexus 5X emulator
> 
>     * OS: android 9

d

**Comment by aniketambore** [comment]
> 
> 
> **To Reproduce**
> Steps to reproduce the behavior:
> 
>     1. Go to Home screen
> 
>     2. Click on Design course (the last item)
> 
>     3. Click to any item
> 
>     4. See issue
> 
> 
> **Expected behavior**
> The course info screen is scrollable when the description text is long
> 
> **Screenshots**
> ![Screenshot_1610078907](https://user-images.githubusercontent.com/4602123/103973390-ea743180-51a1-11eb-8d2c-685a09b76fdc.png)
> 
> **Smartphone (please complete the following information):**
> 
>     * Device: Nexus 5X emulator
> 
>     * OS: android 9

---

This issue is not related to the current code base, check 

```
📁Best-Flutter-UI-Templates
    📁best_flutter_ui_templates
        📁lib
           📁design_course
               🎯course_info_screen.dart - line 179
```
As stated in **🎯course_info_screen.dart - line 179** the **Text** widget is using **maxLines: 3** property, which indicated that If the text exceeds the given number of lines, it will be truncated.

The exact behavior as per the code-base looks something like this
![Screenshot_1612529173](https://user-images.githubusercontent.com/52826253/107036608-ea3a7680-67df-11eb-8fbc-4fa8a66bcf93.png)

**Comment by pd0h** [comment]
.((:
